const { check, validationResult } = require('express-validator/check');

app.get( "/" , 
	[
	  check("input fieldName", "messafe if fails to pass validations").isEmail(or some other validation),
	  check("input field name", "message if fails to pass validation").condition()
	],
 (req, res)=>{
   const errors = validationResult(req);
   if (!errors ){
 	console.error( errors.array() )	
    } 
	........
	........
	........
	........
	........
	........
	........
	........
  })